const words = [
  "Amistad", "Alegría", "Mañana", "Sol", "Estrella", "Amor", "Corazón", 
  "Esperanza", "Sabiduría", "Conocimiento", "Paz", "Naturaleza", "Luna", 
  "Mar", "Tierra", "Viento", "Bosque", "Montaña", "Río", "Lago", "Árbol", 
  "Flor", "Animal", "Serpiente", "Llama", "León", "Delfín", "Elefante", 
  "Perro", "Gato", "Pájaros", "Árbol", "Ocaso", "Amanecer", "Horizonte", 
  "Viaje", "Camino", "Destino", "Aventura", "Desafío", "Éxito", "Fracaso", 
  "Fuerza", "Valentía", "Persistencia", "Resiliencia", "Cambio", "Crecimiento", 
  "Renovación", "Mente", "Alma", "Espíritu", "Sentimiento", "Idea", 
  "Pensamiento", "Reflexión", "Sabio", "Inteligencia", "Curiosidad", "Cielo", 
  "Estación", "Invierno", "Primavera", "Verano", "Otoño", "Solución", 
  "Problema", "Desafío", "Oportunidad", "Éxito", "Esperanza", "Sueño", "Meta", 
  "Propósito", "Libertad", "Justicia", "Igualdad", "Democracia", "Familia", 
  "Amante", "Pareja", "Amigo", "Compañero", "Comida", "Agua", "Bebida", 
  "Cena", "Desayuno", "Almuerzo", "Fruta", "Verdura", "Carne", "Pescado", 
  "Pan", "Arroz", "Pasta", "Aceite", "Sal", "Azúcar", "Harina", "Leche", 
  "Café", "Té", "Chocolate", "Dulce", "Postre", "Fiesta", "Celebración", 
  "Boda", "Cumpleaños", "Aniversario", "Fiesta", "Música", "Canción", "Baile", 
  "Instrumento", "Melodía", "Ritmo", "Letra", "Poema", "Pintura", "Escultura", 
  "Arte", "Creatividad", "Diseño", "Estilo", "Moda", "Ropa", "Zapatos", 
  "Sombrero", "Guantes", "Bufanda", "Abrigo", "Camiseta", "Pantalón", "Falda", 
  "Vestido", "Traje", "Chaqueta", "Corbata", "Collar", "Pulsera", "Anillo", 
  "Joya", "Perfume", "Cosmético", "Maquillaje", "Belleza", "Estética", "Salud", 
  "Ejercicio", "Deporte", "Fútbol", "Baloncesto", "Tenis", "Natación", "Atletismo", 
  "Gimnasio", "Yoga", "Meditación", "Relajación", "Sueño", "Cansancio", "Energía", 
  "Fuerza", "Voluntad", "Coraje", "Despertar", "Estudio", "Escuela", "Maestro", 
  "Alumno", "Clase", "Examen", "Tarea", "Nota", "Grado", "Carrera", "Universidad", 
  "Libro", "Historia", "Ciencia", "Matemática", "Lengua", "Geografía", "Física", 
  "Química", "Biología", "Filosofía", "Política", "Economía", "Derecho", "Medicina", 
  "Tecnología", "Computadora", "Internet", "Red", "Software", "Hardware", 
  "Aplicación"
]
